Multiclass Logistic regression

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from sklearn.datasets import make_classification

In [3]:
X,y = make_classification(n_samples=1000,n_classes=3,n_features=20,n_informative=15,n_redundant=5,random_state=1)

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=1)

In [5]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()


In [6]:
logistic.fit(X_train,y_train)
y_pred = logistic.predict(X_test)

In [7]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score,f1_score
score = accuracy_score(y_test,y_pred)
print('Accuracy : ',score)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(f1_score(y_test,y_pred,average='micro'))

Accuracy :  0.82
[[80  4  7]
 [16 78  5]
 [12 10 88]]
              precision    recall  f1-score   support

           0       0.74      0.88      0.80        91
           1       0.85      0.79      0.82        99
           2       0.88      0.80      0.84       110

    accuracy                           0.82       300
   macro avg       0.82      0.82      0.82       300
weighted avg       0.83      0.82      0.82       300

0.82
